### PR TITLE
fix for label in dataset

### PR DESCRIPTION
**Pull request by orcema**
The graphics do not show up due to missing column lable Date
image

### CODE REVIEW

**Comment by orcema** [comment]
Without the fix i get this error

image

**Comment by orcema** [comment]
when using the "dash_lab" library i get the error here below, finaly it worked for me with this fix
image

**Comment by Coding-with-Adam** [comment]
Thank you @orcema . Have you been working with Dash for a while?

**Comment by orcema** [comment]
Hi Adam, no I'm new to Dash but it's an amazing framework that i will try to learn more in deep.

**Comment by Coding-with-Adam** [comment]
Wonderful. That's great to hear, @orcema . 
Don't forget to join the Plotly Dash forum: https://community.plotly.com/
This is a great place to learn Dash with the community and get support when needed. 

Let me know when you create an account on the forum and we can continue our conversation there if you'd like.

**Comment by orcema** [comment]
I joined now the Plotly Dash forum.

**Comment by mboiwahab** [comment]
No I am new to dash

**Pull request merged**
